# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

package:
  stage: build
  script:
   - npm i && (cd app && npm i)
   - npx electron-builder -l deb
  artifacts:
    expire_in: 1 week
    when: always
    paths:
     - dist/*.deb
