name: teams-for-linux
version: '0.2.1'
summary: Unofficial Microsoft Teams client for Linux
description: |
  Unofficial Microsoft Teams client for Linux using Electron. 
  It uses the Web App and wraps it as a standalone application using Electron.
base: core18
grade: stable
confinement: strict
architectures:
  - amd64

parts:
  teams-for-linux:
    source: .
    # See 'snapcraft plugins'
    plugin: nodejs
    # node-engine: '10.15.3'
    # node-package-manager: yarn
    stage-packages:
      - python
      - build-essential
      - hunspell

apps:
  teams-for-linux:
    command: $SNAP/teams-for-linux
    plugs:
      - browser-support
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - pulseaudio
      - unity7
      - x11