
  name: teams-for-linux-isma
  version: '0.2.1'
  summary: teams-for-linux
  description: |
    Unofficial Microsoft Teams client for Linux using Electron. 
    It uses the Web App and wraps it as a standalone application using Electron.

  grade: stable
  confinement: strict

  parts:
    teams-for-linux:
      # See 'snapcraft plugins'
      plugin: nodejs
      node-engine: '8.9.4'
      node-package-manager: yarn
      source: .
  
  apps:
    teams-for-linux:
      command: bin/teams-for-linux
      plugs: ['network','camera']
  
